export const categoryIcons = {
  "General Knowledge": "👨‍🎓",
  "Entertainment: Books": "🧙‍",
  "Entertainment: Film": "🎬",
  "Entertainment: Music": "🎙️",
  "Entertainment: Musicals & Theatres": "🎭",
  "Entertainment: Television": "🖥️",
  "Entertainment: Video Games": "🕹️",
  "Entertainment: Board Games": "🎲",
  "Science & Nature": "🌀",
  "Science: Computer": "💾",
  "Science: Mathematics": "🤓",
  Mythology: "🔱",
  Sports: "🏆",
  Geography: "🌍",
  History: "🗿",
  Politics: "🧛‍",
  Art: "👨‍🎨‍",
  Celebrities: "👩‍🎤‍",
  Animals: "🐵",
  Vehicles: "🚂",
  "Entertainment: Comics": "🤖",
  "Science: Gadgets": "📡",
  "Entertainment: Japanese Anime & Manga": "⛩️",
  "Entertainment: Cartoon & Animations": "👻",
};
